FROM node:18.20-bullseye
WORKDIR /frontend
COPY frontend/package.json /frontend/
COPY frontend/yarn.lock /frontend/
COPY frontend/ckeditor /frontend/ckeditor
COPY frontend/@types /frontend/@types
RUN yarn install --frozen-lockfile
COPY frontend /frontend
RUN yarn build

FROM nginx:alpine
RUN apk add --no-cache util-linux
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=0 /frontend/build .
COPY --from=0 /frontend/env.template.js .

COPY contrib/nginx.conf /etc/nginx/conf.d/default.conf
RUN chown root:root /etc/nginx/conf.d/default.conf && chmod 755 /etc/nginx/conf.d/default.conf
ARG version="__DEV__"
ENV APP_VERSION $version
ADD ./frontend_entrypoint.sh /usr/share/nginx/frontend_entrypoint.sh
RUN chmod +x /usr/share/nginx/frontend_entrypoint.sh
CMD ["/usr/share/nginx/frontend_entrypoint.sh"]
