export const countries = {
    AF: { label: "Afghanistan", prefix: "" },
    AL: { label: "Albania", prefix: "" },
    DZ: { label: "Algeria", prefix: "" },
    AS: { label: "American Samoa", prefix: "" },
    AD: { label: "Andorra", prefix: "" },
    AO: { label: "Angola", prefix: "" },
    AI: { label: "Anguilla", prefix: "" },
    AQ: { label: "Antarctica", prefix: "" },
    AG: { label: "Antigua and Barbuda", prefix: "" },
    AR: { label: "Argentina", prefix: "" },
    AM: { label: "Armenia", prefix: "" },
    AW: { label: "Aruba", prefix: "" },
    AU: { label: "Australia", prefix: "" },
    AT: { label: "Austria", prefix: "" },
    AZ: { label: "Azerbaijan", prefix: "" },
    BS: { label: "Bahamas", prefix: "the" },
    BH: { label: "Bahrain", prefix: "" },
    BD: { label: "Bangladesh", prefix: "" },
    BB: { label: "Barbados", prefix: "" },
    BY: { label: "Belarus", prefix: "" },
    BE: { label: "Belgium", prefix: "" },
    BZ: { label: "Belize", prefix: "" },
    BJ: { label: "Benin", prefix: "" },
    BM: { label: "Bermuda", prefix: "" },
    BT: { label: "Bhutan", prefix: "" },
    BO: { label: "Bolivia", prefix: "Plurinational State of" },
    BQ: { label: "Bonaire, Sint Eustatius and Saba", prefix: "" },
    BA: { label: "Bosnia and Herzegovina", prefix: "" },
    BW: { label: "Botswana", prefix: "" },
    BV: { label: "Bouvet Island", prefix: "" },
    BR: { label: "Brazil", prefix: "" },
    IO: { label: "British Indian Ocean Territory", prefix: "the" },
    BN: { label: "Brunei Darussalam", prefix: "" },
    BG: { label: "Bulgaria", prefix: "" },
    BF: { label: "Burkina Faso", prefix: "" },
    BI: { label: "Burundi", prefix: "" },
    CV: { label: "Cabo Verde", prefix: "" },
    KH: { label: "Cambodia", prefix: "" },
    CM: { label: "Cameroon", prefix: "" },
    CA: { label: "Canada", prefix: "" },
    KY: { label: "Cayman Islands", prefix: "the" },
    CF: { label: "Central African Republic", prefix: "the" },
    TD: { label: "Chad", prefix: "" },
    CL: { label: "Chile", prefix: "" },
    CN: { label: "China", prefix: "" },
    CX: { label: "Christmas Island", prefix: "" },
    CC: { label: "Cocos (Keeling) Islands", prefix: "the" },
    CO: { label: "Colombia", prefix: "" },
    KM: { label: "Comoros", prefix: "the" },
    CD: { label: "Congo", prefix: "the Democratic Republic of the" },
    CG: { label: "Congo", prefix: "the" },
    CK: { label: "Cook Islands", prefix: "the" },
    CR: { label: "Costa Rica", prefix: "" },
    HR: { label: "Croatia", prefix: "" },
    CU: { label: "Cuba", prefix: "" },
    CW: { label: "Curaçao", prefix: "" },
    CY: { label: "Cyprus", prefix: "" },
    CZ: { label: "Czechia", prefix: "" },
    CI: { label: "Côte d'Ivoire", prefix: "" },
    DK: { label: "Denmark", prefix: "" },
    DJ: { label: "Djibouti", prefix: "" },
    DM: { label: "Dominica", prefix: "" },
    DO: { label: "Dominican Republic", prefix: "the" },
    EC: { label: "Ecuador", prefix: "" },
    EG: { label: "Egypt", prefix: "" },
    SV: { label: "El Salvador", prefix: "" },
    GQ: { label: "Equatorial Guinea", prefix: "" },
    ER: { label: "Eritrea", prefix: "" },
    EE: { label: "Estonia", prefix: "" },
    SZ: { label: "Eswatini", prefix: "" },
    ET: { label: "Ethiopia", prefix: "" },
    FK: { label: "Falkland Islands (the) [Malvinas]", prefix: "" },
    FO: { label: "Faroe Islands", prefix: "the" },
    FJ: { label: "Fiji", prefix: "" },
    FI: { label: "Finland", prefix: "" },
    FR: { label: "France", prefix: "" },
    GF: { label: "French Guiana", prefix: "" },
    PF: { label: "French Polynesia", prefix: "" },
    TF: { label: "French Southern Territories", prefix: "the" },
    GA: { label: "Gabon", prefix: "" },
    GM: { label: "Gambia", prefix: "the" },
    GE: { label: "Georgia", prefix: "" },
    DE: { label: "Germany", prefix: "" },
    GH: { label: "Ghana", prefix: "" },
    GI: { label: "Gibraltar", prefix: "" },
    GR: { label: "Greece", prefix: "" },
    GL: { label: "Greenland", prefix: "" },
    GD: { label: "Grenada", prefix: "" },
    GP: { label: "Guadeloupe", prefix: "" },
    GU: { label: "Guam", prefix: "" },
    GT: { label: "Guatemala", prefix: "" },
    GG: { label: "Guernsey", prefix: "" },
    GN: { label: "Guinea", prefix: "" },
    GW: { label: "Guinea-Bissau", prefix: "" },
    GY: { label: "Guyana", prefix: "" },
    HT: { label: "Haiti", prefix: "" },
    HM: { label: "Heard Island and McDonald Islands", prefix: "" },
    VA: { label: "Holy See", prefix: "the" },
    HN: { label: "Honduras", prefix: "" },
    HK: { label: "Hong Kong", prefix: "" },
    HU: { label: "Hungary", prefix: "" },
    IS: { label: "Iceland", prefix: "" },
    IN: { label: "India", prefix: "" },
    ID: { label: "Indonesia", prefix: "" },
    IR: { label: "Iran", prefix: "Islamic Republic of" },
    IQ: { label: "Iraq", prefix: "" },
    IE: { label: "Ireland", prefix: "" },
    IM: { label: "Isle of Man", prefix: "" },
    IL: { label: "Israel", prefix: "" },
    IT: { label: "Italy", prefix: "" },
    JM: { label: "Jamaica", prefix: "" },
    JP: { label: "Japan", prefix: "" },
    JE: { label: "Jersey", prefix: "" },
    JO: { label: "Jordan", prefix: "" },
    KZ: { label: "Kazakhstan", prefix: "" },
    KE: { label: "Kenya", prefix: "" },
    KI: { label: "Kiribati", prefix: "" },
    KP: { label: "Korea", prefix: "the Democratic People's Republic of" },
    KR: { label: "Korea", prefix: "the Republic of" },
    KW: { label: "Kuwait", prefix: "" },
    KG: { label: "Kyrgyzstan", prefix: "" },
    LA: { label: "Lao People's Democratic Republic", prefix: "the" },
    LV: { label: "Latvia", prefix: "" },
    LB: { label: "Lebanon", prefix: "" },
    LS: { label: "Lesotho", prefix: "" },
    LR: { label: "Liberia", prefix: "" },
    LY: { label: "Libya", prefix: "" },
    LI: { label: "Liechtenstein", prefix: "" },
    LT: { label: "Lithuania", prefix: "" },
    LU: { label: "Luxembourg", prefix: "" },
    MO: { label: "Macao", prefix: "" },
    MG: { label: "Madagascar", prefix: "" },
    MW: { label: "Malawi", prefix: "" },
    MY: { label: "Malaysia", prefix: "" },
    MV: { label: "Maldives", prefix: "" },
    ML: { label: "Mali", prefix: "" },
    MT: { label: "Malta", prefix: "" },
    MH: { label: "Marshall Islands", prefix: "the" },
    MQ: { label: "Martinique", prefix: "" },
    MR: { label: "Mauritania", prefix: "" },
    MU: { label: "Mauritius", prefix: "" },
    YT: { label: "Mayotte", prefix: "" },
    MX: { label: "Mexico", prefix: "" },
    FM: { label: "Micronesia", prefix: "Federated States of" },
    MD: { label: "Moldova", prefix: "the Republic of" },
    MC: { label: "Monaco", prefix: "" },
    MN: { label: "Mongolia", prefix: "" },
    ME: { label: "Montenegro", prefix: "" },
    MS: { label: "Montserrat", prefix: "" },
    MA: { label: "Morocco", prefix: "" },
    MZ: { label: "Mozambique", prefix: "" },
    MM: { label: "Myanmar", prefix: "" },
    NA: { label: "Namibia", prefix: "" },
    NR: { label: "Nauru", prefix: "" },
    NP: { label: "Nepal", prefix: "" },
    NL: { label: "Netherlands", prefix: "the" },
    NC: { label: "New Caledonia", prefix: "" },
    NZ: { label: "New Zealand", prefix: "" },
    NI: { label: "Nicaragua", prefix: "" },
    NE: { label: "Niger", prefix: "the" },
    NG: { label: "Nigeria", prefix: "" },
    NU: { label: "Niue", prefix: "" },
    NF: { label: "Norfolk Island", prefix: "" },
    MP: { label: "Northern Mariana Islands", prefix: "the" },
    NO: { label: "Norway", prefix: "" },
    OM: { label: "Oman", prefix: "" },
    PK: { label: "Pakistan", prefix: "" },
    PW: { label: "Palau", prefix: "" },
    PS: { label: "Palestine, State of", prefix: "" },
    PA: { label: "Panama", prefix: "" },
    PG: { label: "Papua New Guinea", prefix: "" },
    PY: { label: "Paraguay", prefix: "" },
    PE: { label: "Peru", prefix: "" },
    PH: { label: "Philippines", prefix: "the" },
    PN: { label: "Pitcairn", prefix: "" },
    PL: { label: "Poland", prefix: "" },
    PT: { label: "Portugal", prefix: "" },
    PR: { label: "Puerto Rico", prefix: "" },
    QA: { label: "Qatar", prefix: "" },
    MK: { label: "Republic of North Macedonia", prefix: "" },
    RO: { label: "Romania", prefix: "" },
    RU: { label: "Russian Federation", prefix: "the" },
    RW: { label: "Rwanda", prefix: "" },
    RE: { label: "Réunion", prefix: "" },
    BL: { label: "Saint Barthélemy", prefix: "" },
    SH: { label: "Saint Helena, Ascension and Tristan da Cunha", prefix: "" },
    KN: { label: "Saint Kitts and Nevis", prefix: "" },
    LC: { label: "Saint Lucia", prefix: "" },
    MF: { label: "Saint Martin", prefix: "French part" },
    PM: { label: "Saint Pierre and Miquelon", prefix: "" },
    VC: { label: "Saint Vincent and the Grenadines", prefix: "" },
    WS: { label: "Samoa", prefix: "" },
    SM: { label: "San Marino", prefix: "" },
    ST: { label: "Sao Tome and Principe", prefix: "" },
    SA: { label: "Saudi Arabia", prefix: "" },
    SN: { label: "Senegal", prefix: "" },
    RS: { label: "Serbia", prefix: "" },
    SC: { label: "Seychelles", prefix: "" },
    SL: { label: "Sierra Leone", prefix: "" },
    SG: { label: "Singapore", prefix: "" },
    SX: { label: "Sint Maarten", prefix: "Dutch part" },
    SK: { label: "Slovakia", prefix: "" },
    SI: { label: "Slovenia", prefix: "" },
    SB: { label: "Solomon Islands", prefix: "" },
    SO: { label: "Somalia", prefix: "" },
    ZA: { label: "South Africa", prefix: "" },
    GS: { label: "South Georgia and the South Sandwich Islands", prefix: "" },
    SS: { label: "South Sudan", prefix: "" },
    ES: { label: "Spain", prefix: "" },
    LK: { label: "Sri Lanka", prefix: "" },
    SD: { label: "Sudan", prefix: "the" },
    SR: { label: "Suriname", prefix: "" },
    SJ: { label: "Svalbard and Jan Mayen", prefix: "" },
    SE: { label: "Sweden", prefix: "" },
    CH: { label: "Switzerland", prefix: "" },
    SY: { label: "Syrian Arab Republic", prefix: "" },
    TW: { label: "Taiwan", prefix: "" },
    TJ: { label: "Tajikistan", prefix: "" },
    TZ: { label: "Tanzania, United Republic of", prefix: "" },
    TH: { label: "Thailand", prefix: "" },
    TL: { label: "Timor-Leste", prefix: "" },
    TG: { label: "Togo", prefix: "" },
    TK: { label: "Tokelau", prefix: "" },
    TO: { label: "Tonga", prefix: "" },
    TT: { label: "Trinidad and Tobago", prefix: "" },
    TN: { label: "Tunisia", prefix: "" },
    TR: { label: "Turkey", prefix: "" },
    TM: { label: "Turkmenistan", prefix: "" },
    TC: { label: "Turks and Caicos Islands", prefix: "the" },
    TV: { label: "Tuvalu", prefix: "" },
    UG: { label: "Uganda", prefix: "" },
    UA: { label: "Ukraine", prefix: "" },
    AE: { label: "United Arab Emirates", prefix: "the" },
    GB: {
        label: "United Kingdom of Great Britain and Northern Ireland",
        prefix: "the",
    },
    UM: { label: "United States Minor Outlying Islands", prefix: "the" },
    US: { label: "United States of America", prefix: "the" },
    UY: { label: "Uruguay", prefix: "" },
    UZ: { label: "Uzbekistan", prefix: "" },
    VU: { label: "Vanuatu", prefix: "" },
    VE: { label: "Venezuela", prefix: "Bolivarian Republic of" },
    VN: { label: "Viet Nam", prefix: "" },
    VG: { label: "Virgin Islands", prefix: "British" },
    VI: { label: "Virgin Islands", prefix: "U.S." },
    WF: { label: "Wallis and Futuna", prefix: "" },
    EH: { label: "Western Sahara", prefix: "" },
    YE: { label: "Yemen", prefix: "" },
    ZM: { label: "Zambia", prefix: "" },
    ZW: { label: "Zimbabwe", prefix: "" },
    AX: { label: "Åland Islands", prefix: "" },
};

export const employeeListfilterNames = [
    "team",
    "manager",
    "position",
    "organization",
    "cooperation_type",
    "role",
];
